"""
ArmSight — Deployment Package Generator
Generates a Dockerized FastAPI inference server targeting linux/arm64.
"""
from __future__ import annotations

import os
import textwrap
from typing import Any


DOCKERFILE_TEMPLATE = """\
# ArmSight Generated Deployment — Arm64 Optimized Inference Server
# Build: docker buildx build --platform linux/arm64 -t {image_name} .
# Run:   docker run --rm -p 8000:8000 {image_name}
FROM --platform=linux/arm64 python:3.11-slim

WORKDIR /app

# Install onnxruntime (CPU EP with NEON support on Arm64)
RUN pip install --no-cache-dir \\
    fastapi==0.115.6 \\
    uvicorn[standard]==0.34.0 \\
    onnxruntime==1.20.1 \\
    numpy==1.26.4 \\
    python-multipart==0.0.20

# Copy model and server
COPY {model_filename} /app/model.onnx
COPY server.py /app/server.py

# Expose inference port
EXPOSE 8000

# Optimized for Arm64: set thread count via env (default 4 for Graviton)
ENV OMP_NUM_THREADS=4
ENV OMP_WAIT_POLICY=PASSIVE

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
"""

SERVER_TEMPLATE = """\
\"\"\"
ArmSight Generated Inference Server — Arm64 Optimized
Auto-generated by ArmSight. Accepts input tensors, runs inference, returns outputs.
\"\"\"
import numpy as np
import onnxruntime as ort
from fastapi import FastAPI, UploadFile
from pydantic import BaseModel

app = FastAPI(title="ArmSight Inference Server", version="1.0.0")

# Load model with Arm64 optimizations
_session_options = ort.SessionOptions()
_session_options.intra_op_num_threads = int(__import__("os").environ.get("OMP_NUM_THREADS", "4"))
_session_options.inter_op_num_threads = 1
_session_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL

_session = ort.InferenceSession(
    "/app/model.onnx",
    sess_options=_session_options,
    providers=["CPUExecutionProvider"],
)

class InferRequest(BaseModel):
    input_name: str
    data: list
    dtype: str = "float32"

@app.get("/health")
def health():
    return {{\"status\": \"ok\", \"model_loaded\": True}}

@app.get("/info")
def info():
    return {{
        \"inputs\": [{{\"name\": i.name, \"shape\": i.shape, \"type\": str(i.type)}} for i in _session.get_inputs()],
        \"outputs\": [{{\"name\": o.name, \"shape\": o.shape, \"type\": str(o.type)}} for o in _session.get_outputs()],
    }}

@app.post("/infer")
def infer(req: InferRequest):
    arr = np.array(req.data, dtype=req.dtype)
    outputs = _session.run(None, {{req.input_name: arr}})
    return {{
        \"outputs\": [o.tolist() for o in outputs],
        \"output_names\": [o.name for o in _session.get_outputs()],
    }}
"""

BENCHMARK_SCRIPT = """\
#!/usr/bin/env python3
\"\"\"ArmSight benchmark script — measures inference latency on the deployed server.\"\"\"
import time, sys, json, urllib.request

BASE = sys.argv[1] if len(sys.argv) > 1 else "http://localhost:8000"

def bench():
    # Health check
    r = urllib.request.urlopen(f"{BASE}/health")
    assert json.loads(r.read())["status"] == "ok"
    print("[OK] Server healthy")

    # Model info
    r = urllib.request.urlopen(f"{BASE}/info")
    info = json.loads(r.read())
    print(f"[INFO] Inputs: {info['inputs']}")
    print(f"[INFO] Outputs: {info['outputs']}")

    # Dummy inference benchmark
    import numpy as np
    inp = info["inputs"][0]
    shape = [d if isinstance(d, int) and d > 0 else 1 for d in inp["shape"]]
    data = np.random.randn(*shape).astype("float32").tolist()

    payload = json.dumps({{"input_name": inp["name"], "data": data, "dtype": "float32"}}).encode()
    times = []
    for _ in range(20):
        t0 = time.perf_counter()
        req = urllib.request.Request(f"{BASE}/infer", data=payload, headers={{"Content-Type": "application/json"}})
        urllib.request.urlopen(req)
        t1 = time.perf_counter()
        times.append((t1 - t0) * 1000)

    import statistics
    print(f"\\n[BENCHMARK] Latency mean: {{statistics.mean(times):.2f}}ms")
    print(f"[BENCHMARK] Latency p50:  {{statistics.median(times):.2f}}ms")
    print(f"[BENCHMARK] Throughput:   {{1000/statistics.mean(times):.1f}} ops/sec")

if __name__ == "__main__":
    bench()
"""

DOCKER_COMPOSE = """\
version: "3.9"
services:
  armsight-inference:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    ports:
      - "8000:8000"
    environment:
      - OMP_NUM_THREADS=4
    restart: unless-stopped
"""


def generate_deployment_package(
    model_path: str,
    output_dir: str,
    image_name: str = "armsight-inference",
) -> dict[str, Any]:
    """Generate a complete deployment package for the model."""
    os.makedirs(output_dir, exist_ok=True)

    model_filename = "model.onnx"
    dest_model = os.path.join(output_dir, model_filename)

    # Copy model
    import shutil
    shutil.copy2(model_path, dest_model)

    # Write Dockerfile
    dockerfile_path = os.path.join(output_dir, "Dockerfile")
    with open(dockerfile_path, "w") as f:
        f.write(DOCKERFILE_TEMPLATE.format(image_name=image_name, model_filename=model_filename))

    # Write server.py
    server_path = os.path.join(output_dir, "server.py")
    with open(server_path, "w") as f:
        f.write(SERVER_TEMPLATE)

    # Write benchmark script
    bench_path = os.path.join(output_dir, "benchmark.py")
    with open(bench_path, "w") as f:
        f.write(BENCHMARK_SCRIPT)
    os.chmod(bench_path, 0o755)

    # Write docker-compose.yml
    compose_path = os.path.join(output_dir, "docker-compose.yml")
    with open(compose_path, "w") as f:
        f.write(DOCKER_COMPOSE)

    # Write README
    readme_path = os.path.join(output_dir, "README.md")
    with open(readme_path, "w") as f:
        f.write(textwrap.dedent(f"""\
        # ArmSight Deployment Package — {image_name}

        Arm64-optimized inference server generated by ArmSight.

        ## Quick Start

        ```bash
        # Build for Arm64 (cross-platform with buildx)
        docker buildx build --platform linux/arm64 -t {image_name} .

        # Run
        docker run --rm -p 8000:8000 {image_name}

        # Benchmark
        python benchmark.py http://localhost:8000
        ```

        ## Endpoints

        - `GET  /health` — health check
        - `GET  /info`   — model input/output info
        - `POST /infer`  — run inference

        ## Arm64 Optimizations Applied

        - ONNX Runtime CPU EP with NEON SIMD
        - Configurable thread parallelism (OMP_NUM_THREADS)
        - Full graph optimization level enabled
        - INT8 quantization (if applied before packaging)
        """))

    files = [model_filename, "Dockerfile", "server.py", "benchmark.py", "docker-compose.yml", "README.md"]

    return {
        "output_dir": output_dir,
        "files": files,
        "image_name": image_name,
        "model_filename": model_filename,
        "dockerfile": dockerfile_path,
        "ok": True,
    }
